In [12]:
import pandas as pd
from pathlib import Path

In [13]:
data_path = Path.cwd().parent.joinpath("artifacts/features/train.csv")
df = pd.read_csv(data_path)
df.head()

,-0.5219756496159262,-0.26225719995201097,-1.3722359604962429,-0.2951438623048331,1.0,0.0,0.0.1,0.0.2,0.0.3,0.0.4,0.0.5,0.0.6,1.0.1,0.0.7,0.0.8,0.0.9,0.0.10,0.0.11,0.31177012767581735,0.0.12
0,0.337478,-0.503635,0.194486,-1.349911,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.224365,0.0
1,-0.809013,-0.749883,-1.274104,-0.295144,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.262774,0.0
2,0.284384,-0.172722,-0.683623,0.232240,0.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.220779,0.0
3,-0.676279,-0.989374,-0.842664,-1.877295,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.220883,0.0
4,0.483485,1.271067,-0.100755,0.759623,1.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.251830,0.0

In [14]:
df.columns

Index(['-0.5219756496159262', '-0.26225719995201097', '-1.3722359604962429',
       '-0.2951438623048331', '1.0', '0.0', '0.0.1', '0.0.2', '0.0.3', '0.0.4',
       '0.0.5', '0.0.6', '1.0.1', '0.0.7', '0.0.8', '0.0.9', '0.0.10',
       '0.0.11', '0.31177012767581735', '0.0.12'],
      dtype='object')

In [15]:
data_path = Path.cwd().parent.joinpath("data/raw/clean_customer_churn.parquet")
df = pd.read_parquet(data_path)
df.head()

,City,Gender,Senior Citizen,Partner,Dependents,Tenure Months,Phone Service,Multiple Lines,Internet Service,Online Security,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,Los Angeles,Male,No,No,No,2,Yes,No,DSL,Yes,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,Los Angeles,Female,No,No,Yes,2,Yes,No,Fiber optic,No,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,Los Angeles,Female,No,No,Yes,8,Yes,Yes,Fiber optic,No,...,Month-to-month,Yes,Electronic check,99.65,820.50,Yes,1,86,5372,Moved
3,Los Angeles,Female,No,Yes,Yes,28,Yes,Yes,Fiber optic,No,...,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved
4,Los Angeles,Male,No,No,Yes,49,Yes,Yes,Fiber optic,No,...,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.30,Yes,1,89,5340,Competitor had better devices

In [18]:
df["Churn Value"].value_counts()

Churn Value
0    5174
1    1869
Name: count, dtype: int64

### Calculate `scale_pos_value`

In [19]:
len(df[df["Churn Value"] == 0]) / len(df[df["Churn Value"] == 1])

2.7683253076511503